<?php

declare(strict_types=1);

namespace SilenZ\Segmatch\Internal;

use SilenZ\Segmatch\Compiler;
use UnitEnum;

use function array_is_list;
use function implode;
use function is_array;
use function var_export;

/**
 * Renders compiled routes as a PHP file that returns the structure unchanged: one line per table
 * entry, with a short comment above each table, so the file stays small and still readable.
 *
 * @internal
 *
 * @psalm-import-type CompiledRoutes from Compiler
 */
final class Exporter
{
    private const array TABLES = [
        'static' => 'full path => route id(s), for routes without parameters',
        'edges' => 'node => static segment => child node (node 0 is the root)',
        'param' => 'node => child node of its {param} edge',
        'catch' => 'node => route id(s) of its catch-all edge, or [ids, true] for {name+}',
        'routes' => 'node => route id(s) ending there',
        'metadata' => 'route id => metadata',
        'paramNames' => 'route id => parameter names, in capture order',
    ];

    /**
     * @param CompiledRoutes $compiled
     */
    public static function export(array $compiled): string
    {
        $lines = [
            '<?php',
            '',
            '// Generated by silenz/segmatch. Do not edit.',
            '',
            'declare(strict_types=1);',
            '',
            'return [',
            "    'version' => " . var_export($compiled['version'], return: true) . ',',
            '',
            '    // metadata of the route table as a whole, not of any one route',
            "    'table' => " . self::inline($compiled['table']) . ',',
        ];

        foreach (self::TABLES as $name => $description) {
            $table = $compiled[$name];
            $lines[] = '';
            $lines[] = '    // ' . $description;
            if ($table === []) {
                $lines[] = '    ' . var_export($name, return: true) . ' => [],';
                continue;
            }

            $lines[] = '    ' . var_export($name, return: true) . ' => [';
            $list = array_is_list($table);
            // @mago-expect analysis:mixed-assignment
            foreach ($table as $key => $value) {
                $prefix = $list ? '/* ' . $key . ' */ ' : var_export($key, return: true) . ' => ';
                $lines[] = '        ' . $prefix . self::inline($value) . ',';
            }
            $lines[] = '    ],';
        }

        $lines[] = '];';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private static function inline(mixed $value): string
    {
        if (!is_array($value)) {
            return self::scalar($value);
        }

        $list = array_is_list($value);
        $items = [];
        // @mago-expect analysis:mixed-assignment
        foreach ($value as $key => $item) {
            $items[] = ($list ? '' : var_export($key, return: true) . ' => ') . self::inline($item);
        }

        return '[' . implode(', ', $items) . ']';
    }

    private static function scalar(mixed $value): string
    {
        if ($value instanceof UnitEnum) {
            return '\\' . $value::class . '::' . $value->name;
        }

        return var_export($value, return: true);
    }
}
