<?php

declare(strict_types=1);

namespace silenz\PhpRouter\Internal;

use silenz\PhpRouter\Compiler;
use UnitEnum;

use function array_is_list;
use function implode;
use function is_array;
use function str_repeat;
use function var_export;

/**
 * Renders compiled routes as a readable PHP file that returns the structure unchanged.
 *
 * @internal
 *
 * @psalm-import-type CompiledRoutes from Compiler
 */
final class Exporter
{
    /**
     * @param CompiledRoutes $compiled
     */
    public static function export(array $compiled): string
    {
        $static = [];
        foreach ($compiled['static'] as $path => $entry) {
            $static[] = '        ' . var_export($path, return: true) . ' => ' . self::inline($entry) . ',';
        }

        $nodes = [];
        foreach ($compiled['nodes'] as $id => $node) {
            $nodes[] = '        /* ' . $id . ' */ ' . self::inline($node) . ',';
        }

        return implode("\n", [
            '<?php',
            '',
            '// Generated by phrach/php-router. Do not edit.',
            '',
            'declare(strict_types=1);',
            '',
            'return [',
            "    'version' => " . var_export($compiled['version'], return: true) . ',',
            "    'static' => [",
            ...$static,
            '    ],',
            "    'nodes' => [",
            ...$nodes,
            '    ],',
            "    'routes' => " . self::pretty($compiled['routes'], 1) . ',',
            '];',
            '',
        ]);
    }

    private static function inline(mixed $value): string
    {
        if (!is_array($value)) {
            return self::scalar($value);
        }

        $list = array_is_list($value);
        $items = [];
        // @mago-expect analysis:mixed-assignment
        foreach ($value as $key => $item) {
            $items[] = ($list ? '' : var_export($key, return: true) . ' => ') . self::inline($item);
        }

        return '[' . implode(', ', $items) . ']';
    }

    /**
     * @param non-negative-int $depth
     */
    private static function pretty(mixed $value, int $depth): string
    {
        if (!is_array($value)) {
            return self::scalar($value);
        }

        if ($value === []) {
            return '[]';
        }

        $list = array_is_list($value);
        $indent = str_repeat('    ', $depth + 1);
        $lines = ['['];
        // @mago-expect analysis:mixed-assignment
        foreach ($value as $key => $item) {
            $lines[] =
                $indent
                . ($list ? '' : var_export($key, return: true) . ' => ')
                . self::pretty($item, $depth + 1)
                . ',';
        }
        $lines[] = str_repeat('    ', $depth) . ']';

        return implode("\n", $lines);
    }

    private static function scalar(mixed $value): string
    {
        if ($value instanceof UnitEnum) {
            return '\\' . $value::class . '::' . $value->name;
        }

        return var_export($value, return: true);
    }
}
